version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: jihee_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - ./x:/var/lib/mysql

  fastapi:
    image: sec_project_fastapi
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy  